spring.application.name=kids-fashion-shop


spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/kids_fashion_shop?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8&useUnicode=true}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:tritrongtutien}

app.sepay.bank-id=${SEPAY_BANK_ID:MBBank}
app.sepay.account-number=${SEPAY_ACC_NUMBER:00000000}
app.sepay.account-name=${SEPAY_ACC_NAME:TEN_CHU_TAI_KHOAN}
app.sepay.webhook-token=${SEPAY_WEBHOOK_TOKEN:MY_SECRET_TOKEN}

# Multipart Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

spring.thymeleaf.cache=false

app.hot-score.recalc-ms=300000

app.admin.email=${ADMIN_EMAIL:admin@kidfashion.local}
app.admin.password=${ADMIN_PASSWORD:admin123}
app.admin.full-name=Quản trị viên


spring.config.import=optional:file:./secrets/google-oauth.properties
server.port=8081